{% set name = "elyra-server" %}
{% set version = "3.14.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra_server-{{ version }}.tar.gz
  sha256: 452cdfd18804cd8df62a899c260245379fa6d29288ae16b8aeaf6b4d89519943

build:
  noarch: python
  entry_points:
    - elyra-metadata = elyra.metadata.metadata_app:MetadataApp.main
    - elyra-pipeline = elyra.cli.pipeline_app:pipeline
    - jupyter-elyra = elyra.elyra_app:launch_instance
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - autopep8 >=1.5.0
    - black >=22.8.0
    - click >=8
    - colorama
    - deprecation
    - entrypoints >=0.3
    - jinja2 >=3
    - jsonschema >=3.2.0
    - jupyter_client >=6.1.7
    - jupyter_core >=4.11.0
    - jupyter_events >=0.6.2
    - jupyter-packaging >=0.10
    - jupyter-resource-usage >=0.5.1
    - jupyter_server >=1.7.0
    - jupyterlab-git >=0.32,<1.0
    - jupyterlab-lsp >=3.8.0
    - jupyterlab >=3.4.6,<4.0
    - kfp !=1.7.2,<2.0,>=1.7.0
    - markupsafe >=2.1
    - minio >=7.0.0
    - nbclient >=0.5.1
    - nbconvert >=6.5.1
    - nbdime >=3.1,<4.0
    - nbformat >=5.1.2
    - networkx >=2.5.1
    - papermill >=2.3.4
    - pygithub
    - python-lsp-server >=1.1.0
    - pyyaml >=5.3.1
    - requests >=2.25.1
    - rfc3986-validator >=0.1.1
    - tornado >=6.1.0
    - traitlets >=4.3.2
    - typing-extensions <5,>=3.10
    - urllib3 >=1.26.5
    - watchdog >=2.1.3
    - websocket-client
    - yaspin

test:
  imports:
    - elyra_server
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/elyra-server/
  summary: "The elyra-server package provides common core libraries and functions that are required by Elyra's individual extensions. Note: Installing this package alone will not enable the use of Elyra. Please install the 'elyra' package instead. e.g. pip install elyra[all]"
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
