{% set name = "elyra-server" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-server-{{ version }}.tar.gz
  sha256: 4f5945f964f75e97ff2240d029f4da737e66e397ebcc61858f5f6a7515d83af3

build:
  number: 0
  noarch: python
  entry_points:
    - elyra-metadata = elyra.metadata.metadata_app:MetadataApp.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - autopep8
    - entrypoints >=0.3
    - jinja2 >=2.11,<3.0
    - jsonschema >=3.2.0
    - jupyter_core >=4.0,<5.0
    - jupyter_client >=6.1.7
    - jupyterlab >=3.0.0
    - jupyterlab-lsp >=3.0.0
    - jupyter-resource-usage >=0.5.1
    - kfp-notebook ~=0.18.0
    - kfp ==1.1.2
    - kfp-tekton ==0.5.1rc1
    - minio >=5.0.7,<7.0.0
    - nbclient >=0.5.1
    - nbconvert >=5.6.1,<6.0
    - papermill >=2.1.3
    - python-language-server[all] >=0.36.2
    - python >=3.6
    - requests >=2.9.1,<3.0
    - rfc3986-validator >=0.1.1
    - traitlets >=4.3.2
    - urllib3 >=1.24.2
    - websocket-client
  pip:
    - jupyterlab-git ==0.30.0b1
    - nbdime >=3.0.0.b1

test:
  imports:
    - elyra

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra provides AI Centric extensions to JupyterLab
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
