{% set name = "elyra-server" %}
{% set version = "2.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra-server-{{ version }}.tar.gz
  sha256: d0743e1bd73c4cd7b45de10b2829516e92ca0eb961927ddbabe793c3fa930ebd

build:
  number: 0
  noarch: python
  entry_points:
    - elyra-metadata = elyra.metadata.metadata_app:MetadataApp.main
    - elyra-pipeline = elyra.cli.pipeline_app:pipeline
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - autopep8 >=1.5.0,<1.5.6
    - black
    - click
    - colorama
    - entrypoints >=0.3
    - jinja2 >=2.11,<3.0
    - jsonschema >=3.2.0
    - jupyter-resource-usage >=0.5.1
    - jupyter_client >=6.1.7
    - jupyter_core >=4.0,<5.0
    - jupyter_server >=1.2.0
    - jupyterlab >=3.0.0
    - jupyterlab-git ==0.30.0
    - jupyterlab-lsp >=3.0.0
    - kfp ==1.3.0
    - kfp-notebook >=0.22.0
    - kfp-tekton ==0.6.0
    - minio >=5.0.7,<7.0.0
    - nbclient >=0.5.1
    - nbconvert >=5.6.1,<6.0
    - nbdime >=3.0.0.b1
    - nbformat >=5.1.2
    - papermill >=2.1.3
    - pygithub
    - python >=3.6
    - python-language-server >=0.36.2
    - pyyaml >=5.3.1,<6.0
    - requests >=2.9.1,<3.0
    - rfc3986-validator >=0.1.1
    - tornado >=6.1.0
    - traitlets >=4.3.2
    - urllib3 >=1.24.2
    - websocket-client
    - yaspin

test:
  imports:
    - elyra

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra provides AI Centric extensions to JupyterLab
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
