{% set name = "elyra-server" %}
{% set version = "3.14.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/elyra_server-{{ version }}.tar.gz
  sha256: 452cdfd18804cd8df62a899c260245379fa6d29288ae16b8aeaf6b4d89519943

build:
  number: 0
  noarch: python
  entry_points:
    - elyra-metadata = elyra.metadata.metadata_app:MetadataApp.main
    - elyra-pipeline = elyra.cli.pipeline_app:pipeline
    - jupyter-elyra = elyra.elyra_app:launch_instance
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatchling
    - pip
    - python >=3.7
  run:
    - autopep8 >=1.5.0
    - black >=22.8.0
    - click >=8
    - colorama
    - deprecation
    - entrypoints >=0.3
    - jinja2 >=3
    - jsonschema >=3.2.0,<4.0
    - jupyter-resource-usage >=0.5.1
    - jupyter_client >=6.1.7
    - jupyter_core >=4.11.2,<5
    - jupyter_events <0.5.0
    - jupyter_server >=1.7.0
    - jupyterlab >=3.4.6,<4.0
    - jupyterlab-git ~=0.32.0
    - jupyterlab-lsp >=3.8.0
    - jupyter-resource-usage >=0.5.1
    - kfp >=1.7.0,<2.0,!=1.7.2
    - kfp-tekton ~=1.3.0
    - MarkupSafe >=2.1
    - minio >=7.0.0
    - nbclient >=0.5.1
    - nbconvert >=6.5.1
    - nbdime ~=3.1
    - nbformat >=5.1.2
    - networkx >=2.5.1
    - papermill >=2.3.4
    - pygithub
    - python >=3.7
    - python-lsp-server[all] >=1.1.0
    - pyyaml >=5.3.1,<6.0
    - requests >=2.25.1
    - rfc3986-validator >=0.1.1
    - tornado >=6.1.0
    - traitlets >=4.3.2
    - typing-extensions >=3.10,<5
    - urllib3 >=1.26.5
    - watchdog >=2.1.3
    - websocket-client
    - yaspin

test:
  imports:
    - elyra

about:
  home: https://github.com/elyra-ai/elyra
  summary: Elyra provides AI Centric extensions to JupyterLab
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akchinSTC
    - lresende
